[server]
name = "irc.localhost"

[[server.listeners]]
name = "plain"
address = "127.0.0.1:6667"

[[server.listeners]]
name = "tls"
address = "127.0.0.1:6697"
tls.cert = "cert.pem"
tls.key = "key.pem"
